apiVersion: v1
kind: Service
metadata:
  name: redis-standalone-external-test
  namespace: ot-operators
  labels:
    app.kubernetes.io/name: redis-standalone-external-test
spec:
  type: NodePort
  selector:
    app: redis
    redis_setup_type: standalone
    role: standalone
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30380

# kubectl apply -f test_redis/redis-standalone-nodeport.yaml
# redis-cli -h <node-ip> -p 30380 SET external:write test
