apiVersion: v1
kind: Service
metadata:
  name: redis-replicas-external-test
  namespace: ot-operators
  labels:
    app.kubernetes.io/name: redis-replicas-external-test
spec:
  type: NodePort
  selector:
    app: redis-replication
    redis_setup_type: replication
    role: replication
    redis-role: slave
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30380

# kubectl apply -f test_redis/redis-replicas-nodeport.yaml - проброска порта 
# Тест redis-cli -h <node-ip> -p 30380 SET external:write test